export const COLORS = {
  APP: {
    BACKGROUND_COLOR: '#FFFFFF',
    STATUS_BAR_COLOR: '#FFFFFF',
    PRIMARY_COLOR: '#FFFFFF',
    SECONDARY_COLOR: '#10B78B',
    TERTIARY_COLOR: '#3068F9',
  },
  TAB: {
    ACTIVE_COLOR: '#10B78B',
    INACTIVE_COLOR: '#BCBCBC',
  },
  HOME: {
    CAROUSEL_COUNTER_BACKGROUND_COLOR: 'rgba(0, 0, 0,0.4)',
    CAROUSEL_COUNTER_COLOR: '#FFFFFF',
    CARD_BACKGROUND_COLOR: '#F3EE76',
    LABEL_COLOR: '#000',
  },
  COMPONENTS: {
    MATERIALIZED_INPUT: {
      BACKGROUND_COLOR: '#FFFFFF',
      ACTIVE_BORDER_COLOR: '#3168F9',
      INACTIVE_BORDER_COLOR: '#DBDBDB',
      TEXT_COLOR: '#0F1828',
      PLACEHOLDER_COLOR: '#D3D3D3',
      LABEL_COLOR: '#3168F9',
    },
    BUTTON: {
      COLOR: '#10B78B',
      TEXT_COLOR: '#FFFFFF',
      DESABLE_COLOR: '#F3F6F6',
      DESABLE_TEXT_COLOR: '#797C7B',
      LOADER_COLOR: '#797C7B',
    },
  },
};
